# ----------- CONFIGURABLE START -----------
title:            "hieuhc's blog"
description:      "Show me the data"
url:              http://hieuhc.me # Site url, without a slash at the end.
signoff:          "hieuhc" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            true # Turn on twitter and facebook share buttons

links:
  - name:         Posts
    url:          /
    external:     false
  - name:         About me
    url:          /about
    external:     false

markdown: kramdown

kramdown:
  parse_block_html: true

permalink:        /posts/:title

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"

# ------------ CONFIGURABLE END ------------